### PR TITLE
feature: swap from `@dataclass` to pydantic `BaseModel`

### PR DESCRIPTION
**Pull request by b-rowan**
There are many advantages to this swap, including custom model serialization, validation of data values, and much better type safety.  Overall should be backwards compatible, but will allow for a lot of nice end user features, like full typing in the OpenAPI schema when used in FastAPI as a return type, model dumps directly to JSON, and generally nicer dict and JSON serialization.

@lejacobroy would like your review on this if you can, this is what I was talking about in your PR, and this should be a much cleaner solution.

### CODE REVIEW

**Comment by b-rowan** [comment]
Also, this shouldn't require direct review, just needs to be bounced off a couple types of miners to make sure nothing is weird.  Have tested on an S9 (BOS+) and it is all working, I will test with more miners shortly.

Here's a script - 
```python3
import pyasic
import asyncio
from pprint import pprint as print

SUBNET = "10.0.0.0/21"

async def main():
    miners = await pyasic.MinerNetwork.from_subnet(SUBNET).scan()

    print(miners)
    data = await asyncio.gather(*[m.get_data() for m in miners])
    print(data)
    print(data[0].model_dump())


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by jpcomps** [comment]
Did a quick check on a small number of miners we had. Looks good. 

print(data[0].model_dump()) --> print(data[0].as_dict()). -- don't think model_dump is exposed, but we can expose it if its useful.

**Comment by b-rowan** [comment]
> print(data[0].model_dump()) --> print(data[0].as_dict()). -- don't think model_dump is exposed, but we can expose it if its useful.

Not sure what you mean?  `model_dump` is exposed as a method of the `pydantic.BaseModel` that everything is inheriting now...

**Comment by eandersson** [comment]
Upgraded and seeing a lot of errors e.g.
> pyasic.errors.APIError: Failed to call config on S19 XP (BOS+): <IP> while getting data.
> pydantic_core._pydantic_core.ValidationError: 1 validation error for MiningModeHashrateTune

**Pull request merged**
