### PR TITLE
feature: improve config handling

### PR DESCRIPTION
**Pull request by UpstreamData**
This PR changes over from the old style of `MinerConfig` to a newer version with much stronger type hinting, as well as having a much friendlier usage API and being much more extensible.

Changes have been made to all miner classes that support configuration, so these should all be able to still be used through the standard "public" API, but this is a breaking change to anything using the config directly or trying to manually send configs.

### CODE REVIEW

**Comment by UpstreamData** [comment]
Closes #73

**Comment by UpstreamData** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/upstreamdata/pyasic) found multiple issues last seen at 27368a9bd28a1b0f23376f686002a1b4cc8f930b:

#### unresolved comment &#39;# TODO: check if this is accurate, user/username, pass/password&#39;
- [ ]  [pyasic\config\pools.py:124](https://github.com/UpstreamData/pyasic/blob/27368a9bd28a1b0f23376f686002a1b4cc8f930b/pyasic/config/pools.py#L124)
- [ ]  [pyasic\config\pools.py:117](https://github.com/UpstreamData/pyasic/blob/27368a9bd28a1b0f23376f686002a1b4cc8f930b/pyasic/config/pools.py#L117)

#### unresolved comment &#39;# TODO: check if this should be a loop, can&#39;t remember.&#39;
- [ ]  [pyasic\miners\innosilicon\cgminer\T3X\T3H.py:288](https://github.com/UpstreamData/pyasic/blob/27368a9bd28a1b0f23376f686002a1b4cc8f930b/pyasic/miners/innosilicon/cgminer/T3X/T3H.py#L288)

**Comment by checksum0** [comment]
Concept ACK. Will run some tests on real machines and complete review by the weekend.

**Comment by b-rowan** [comment]
May have accidentally merged this when trying to merge another branch with small bug fixes that I forgot was based on this branch...  Should be good in any case, @checksum0 if you notice anything wrong with it LMK and I'll get it fixed.

**Pull request merged**
